# -*- Mode: makefile-gmake -*-

EXE = test_retrieve
SRC = $(EXE).c
COMMON_SRC = test_connection.c test_connman.c test_handler.c test_http.c \
  test_transfer_list.c test_util.c

include ../common/Makefile
